### ISSUE TITLE
"altitude" is just set to perigee.

### ISSUE THREAD

**Issue by CharlesPlusC** [ucl-sgnl/FSPSimulator#35]
I think we need to just drop altitude, it's not a real metadata for an orbit because it changes from epoch to epoch. I think maybe best to have an altitude_time_series variable? but we already have an "ephemeris" lis that goes with each object so we can always just use that.

**Comment by CharlesPlusC** [comment]
What about a "circularize" function that just takes orbits with e>0.1 and circulaizes them? How many satellites would this affect? Specifically how many in LEO.

**Comment by blueriver212** [comment]
Alt has been dropped and no longer calculated in the Space Object. For the decay modelling charles has used the ephemeris.
