### ISSUE TITLE
Catalog pulling function issues

### ISSUE THREAD

**Issue by CharlesPlusC** [ucl-sgnl/FSPSimulator#44]
PullCatalogueSpaceTrackActive() pull all satellites not just active satellites
PullCatalogueSpaceTrackAll() only pulls Starlinks. 
There is no API to Celestrak but there are lots of references to Celestrak in the code. Are we manually importing somewhere? Confused.

**Comment by CharlesPlusC** [comment]
SpaceTrack catalog update function is not actually updating the catalog either. Always just uses the local version. What about checking the timestamps of the local file and the SpaceTrack file and if our catalog is more than a week or a month old it gets updated.

**Comment by blueriver212** [comment]
This as fixed a while back
