### ISSUE TITLE
remove_items_from_dict function 

### ISSUE THREAD

**Issue by CharlesPlusC** [ucl-sgnl/FSPSimulator#58]
only "Starlink", "OneWeb", "E-Space" and are not startups? How do we make this assessment and why is it hardcoded? Surely this will just get burried in the code and we wil lforget about it. Also loads of other laaunchers are not startups. Do we plan to manually add them here each time?

**Comment by CharlesPlusC** [comment]
The rate is not used correctly

**Comment by blueriver212** [comment]
I actually dont think this is a very useful function - as if you want to remove certain operators from a simulation, you should just remove it from your starting conditions rather than specifying it within the JSON. Therefore, I have removed it.
