### ISSUE TITLE
No need for "SGP4 long term" parameter in JSON as we no longer use it. There are other "useless" parameters being passed around as well- get rid of them and clean this up.

### ISSUE THREAD

**Issue by CharlesPlusC** [ucl-sgnl/FSPSimulator#76]

**Comment by CharlesPlusC** [comment]
"REMOVE OPERATORS", "FORCE MODEL", "ENVIRONMENT, "

**Comment by CharlesPlusC** [comment]
"SGP4_LONG_TERM", "INTEGRATOR_TYPE"

**Comment by blueriver212** [comment]
{
    "scenario_name": "oneweb_starlink",
    "monthly_ton_capacity": "150",
    "launch_start_date":"2019-01-01",
    "remove_operators": " ",
    "sim_start_date":"2019-01-01",
    "sim_end_date":"2028-01-01",
    "output_frequency": 960000,
    "integrator_step_size": 960000,
    "sim_object_type": "all",
    "sim_object_catalogue" : "both",
    "repull_catalogues": false,
    "satellite_predictions_csv": "oneweb_starlink_test.csv"
  }
  
  This is the now stripped down json input parameter

**Comment by blueriver212** [comment]
I will close this for now, please re-open if you think the above should be changed
